language: go

go:
  - 1.3
  - 1.4
  - tip

install:
  - go get github.com/garyburd/redigo/redis
  - go get github.com/codegangsta/cli
  - go get gopkg.in/check.v1
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script: 
  - go test  -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken tokennnnTODO
